import 'package:flutter/material.dart';

const Color primaryLiteColor = Color(0xFFF6E6E8);
const Color primaryColor = Color(0xffFF5759);
const Color dividerColor = Color(0xFFD9D9D9);
const Color tableHeading = Color(0xFF7E7E7E);
const Color secondaryColor = Color(0xFF3D5A80);
const Color unSelectedTabColor = Color(0xFF484848);
const Color whiteColor = Colors.white70;
const Color lightGrey = Color(0xffD3D3D3);
const Color transparent = Colors.transparent;
final containerColor = Colors.yellow[50];
const white = Colors.white;
const Color green = Colors.green;
final veryLightGrey = Colors.grey[100];
const headingColor = Color(0xFF000000);
const subHeadingColor = Color(0xFF949598);
const appBackgroundColor = Color(0xFFf8f8f8);
const orders1 = Color(0xFFF0FBFA);
const orders2 = Color(0xFFF3F3F3);
const orders3 = Color(0xFFEEEBFA);
const orders4 = Color(0xFFFFEDED);
